[env:bluepill]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo
  adafruit/RTClib
build_flags = -D LED_PIN=PC13
