; LCD1602 (I2C) 上显示 6666 + 大拇指。Freenove ESP32-WROVER，USB-C 直烧。
[env:wrover]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D BOARD_HAS_PSRAM
board_build.partitions = huge_app.csv
lib_deps =
  marcoschwartz/LiquidCrystal_I2C
